# Generated by Django 4.2 on 2023-04-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_r', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='com_loaction',
            new_name='com_location',
        ),
    ]
