# Generated by Django 4.2 on 2023-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_r', '0002_rename_com_loaction_company_com_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_id', models.IntegerField(null=True)),
            ],
        ),
    ]
