# Generated by Django 4.2 on 2023-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_r', '0004_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=266, null=True)),
                ('acc_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
